### PR TITLE
Dashboard page

### PR DESCRIPTION
**Pull request by R4Ajeti**
Hope you are having a good day,

I have cloned serprobot.com dashboard page but to have access on that page you need have an account. I created a free account for you down bellow.
 
Original web: https://www.serprobot.com/user/dashboard.php
Username: gizedu@getvmail.net
Password: gizedu

Best regards,
R!n0

### CODE REVIEW

**Comment by Ispirett** [comment]
# Reviewing

**Review by Ispirett — CHANGES_REQUESTED** [review]
Hey, @R4Ajeti  @RoyNyaga  exceptional work with this project you guys are doing a fantastic job :1st_place_medal:   .There are just a few changes that Mircoverse requires before this project can be completed.**
#### Css errors
- [ ] There are some css errors please use this tool https://jigsaw.w3.org/css-validator/#validate_by_upload and correct them.


#### Display 
**You have already implement display flex, just three more classes** 
* [ ] A class to set the display property to hidden
* [ ] A class to set the display property to none
* [ ] The none class should have breakpoints (example display-md-none)

#### Floats
* [ ] The CSS files define separate classes for float left, right and clearing the floats

#### main tag
**OPTIONAL** not required to complete this project. Consider placing all your main content on the site in a main tag.

**Please solve the issue with the conflicting dashboard.html .**
**You have done a good job using gitflow**

**Optional** not required to complete the project. The readme file needs some more details about the project 
If I wanted to use your framework, what will help me greatly is a little information about how it works.

**Comment by RoyNyaga** [comment]
Added more classes for float, display and visibility in the framework file and also improved the readme file as demanded. We also rectified all the errors in our css files.

**Comment by bolah2009** [comment]
Currently under review

**Review by bolah2009 — APPROVED** [review]
## Congratulations Team :100: :fireworks: 

Nice job, clone looks good to me and CSS framework meets the requirement. :+1: 

#### Friendly reminder: You should use  [Linter](https://github.com/microverseinc/linters-config#linters-config) in this project. However, changing it now would take too much time. Please make sure you use Github/Git Flow and [Linter](https://github.com/microverseinc/linters-config#linters-config) in the next project. You will find instructions in the Pathwright lesson description.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

**Comment by RoyNyaga** [comment]
Thanks man, am happy completing the first module

**Pull request merged**
